repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: 'v2.1.0'
  hooks:
    - id: trailing-whitespace
    - id: check-executables-have-shebangs
    - id: check-merge-conflict
    - id: debug-statements
    - id: end-of-file-fixer
    - id: fix-encoding-pragma
- repo: https://github.com/antonbabenko/pre-commit-terraform
  rev: 'v1.11.0'
  hooks:
  - id: terraform_fmt
  - id: terraform_docs
- repo: https://github.com/jumanjihouse/pre-commit-hooks
  sha: '1.11.0'
  hooks:
    - id: forbid-binary
    - id: markdownlint
    - id: require-ascii
-   repo: https://github.com/pre-commit/mirrors-isort
    rev: 'v4.3.17'
    hooks:
    -   id: isort
